// Build-time pricing snapshot generator.
//
// Twin of generate-plugin-embed.ts, but network-backed: fetch LiteLLM's pricing
// JSON, filter to the provider allowlist, compact to per-token records via the
// sessions-owned parseLiteLLMPricing, and write src/report/pricing-data.generated.ts.
//
// The committed snapshot is the offline floor: if the fetch fails (or yields an
// empty/malformed table), reuse the existing generated file and warn — the build
// never breaks and never ships an empty table. Exit 0 either way.
//
// Determinism: content is compared before writing so a no-op run does not churn
// git (the test `git diff --exit-code` after regeneration depends on this).

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { parseLiteLLMPricing, type ModelPricing } from '../src/report/pricing.ts';

const SOURCE_URL =
  process.env['LITELLM_PRICING_URL'] ??
  'https://raw.githubusercontent.com/BerriAI/litellm/main/model_prices_and_context_window.json';
const FETCH_TIMEOUT_MS = 10_000;

// Locked allowlist — the offline floor only needs the providers we actually log.
// Phase 2's runtime fetch carries the full set.
const PROVIDER_ALLOWLIST = new Set(['anthropic', 'openai', 'moonshotai', 'baseten', 'zai', 'openrouter']);

const outPath = join(import.meta.dir, '..', 'src', 'report', 'pricing-data.generated.ts');

function warn(msg: string): void {
  process.stderr.write(`generate-pricing-embed: ${msg}\n`);
}

// Fetch the source JSON as text, or null on any failure (network, timeout, non-200).
async function fetchSource(url: string): Promise<string | null> {
  try {
    if (url.startsWith('file://') || !/^https?:/.test(url)) {
      // Local override (used by tests): read straight off disk.
      const path = url.startsWith('file://') ? new URL(url).pathname : url;
      return readFileSync(path, 'utf8');
    }
    const ctrl = new AbortController();
    const timer = setTimeout(() => ctrl.abort(), FETCH_TIMEOUT_MS);
    try {
      const res = await fetch(url, { signal: ctrl.signal });
      if (!res.ok) {
        warn(`fetch returned HTTP ${res.status}`);
        return null;
      }
      return await res.text();
    } finally {
      clearTimeout(timer);
    }
  } catch (err) {
    warn(`fetch failed (${err instanceof Error ? err.message : String(err)})`);
    return null;
  }
}

// Keep only allowlisted providers, then compact to per-token ModelPricing.
function compact(json: string): Record<string, ModelPricing> {
  let raw: unknown;
  try {
    raw = JSON.parse(json);
  } catch {
    return {};
  }
  if (raw === null || typeof raw !== 'object') return {};

  const filtered: Record<string, unknown> = {};
  for (const [model, value] of Object.entries(raw as Record<string, unknown>)) {
    if (value === null || typeof value !== 'object') continue;
    const provider = (value as { litellm_provider?: unknown }).litellm_provider;
    if (typeof provider !== 'string' || !PROVIDER_ALLOWLIST.has(provider)) continue;
    filtered[model] = value;
  }
  return parseLiteLLMPricing(JSON.stringify(filtered));
}

// Single-quoted string literal matching the project formatter (oxfmt) style.
const sq = (s: string): string => `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;

// Emit a ModelPricing as a spaced object literal: `{ inputPerToken: 3e-7, ... }`.
// Numbers keep JSON.stringify's rendering; field order follows the interface.
// oxfmt may re-wrap long literals onto multiple lines — the file is run through
// oxfmt after writing (see formatFile) so the committed form is canonical.
const FIELD_ORDER: (keyof ModelPricing)[] = [
  'inputPerToken',
  'outputPerToken',
  'cacheReadPerToken',
  'cacheWritePerToken',
  'inputPerTokenAbove200k',
  'outputPerTokenAbove200k',
  'cacheReadPerTokenAbove200k',
  'cacheWritePerTokenAbove200k',
];
function serializePricing(p: ModelPricing): string {
  const parts: string[] = [];
  for (const field of FIELD_ORDER) {
    const v = p[field];
    if (v !== undefined) parts.push(`${field}: ${JSON.stringify(v)}`);
  }
  return `{ ${parts.join(', ')} }`;
}

// Serialize a stable, sorted, minimal literal so diffs stay readable + deterministic.
function serialize(pricing: Record<string, ModelPricing>, generatedAt: string, sourceCommit: string): string {
  const keys = Object.keys(pricing).sort();
  let body = '';
  for (const k of keys) {
    body += `  ${sq(k)}: ${serializePricing(pricing[k]!)},\n`;
  }
  return (
    '// Auto-generated by scripts/generate-pricing-embed.ts — do not edit manually.\n' +
    '// Regenerate with: bun run generate-pricing-embed\n' +
    `// Source: ${SOURCE_URL}\n` +
    "import type { ModelPricing } from './pricing.ts';\n\n" +
    `export const GENERATED_AT = ${sq(generatedAt)};\n` +
    `export const SOURCE_COMMIT = ${sq(sourceCommit)};\n\n` +
    'export const PRICING: Record<string, ModelPricing> = {\n' +
    body +
    '};\n'
  );
}

// Run the project formatter (oxfmt) over a single file so the committed snapshot
// is byte-identical to what `bun run format` produces — this makes
// `generate-pricing-embed && format:check` (and the regeneration proof) a fixed
// point regardless of oxfmt's internal line-wrapping heuristics.
async function formatFile(path: string): Promise<void> {
  const proc = Bun.spawn(['bunx', 'oxfmt', path], { stdout: 'ignore', stderr: 'ignore' });
  await proc.exited;
}

// Strip GENERATED_AT so two snapshots can be compared on priced content alone
// (a no-op regeneration must not churn git just because the timestamp moved).
function withoutTimestamp(source: string): string {
  return source.replace(/export const GENERATED_AT = '[^']*';\n/, '');
}

// Read GENERATED_AT out of the existing file (single-quoted, oxfmt style).
function existingGeneratedAt(prior: string): string {
  return prior.match(/export const GENERATED_AT = '([^']*)'/)?.[1] ?? new Date().toISOString();
}

// Serialize → write → format-in-place → read back the canonical (oxfmt) form.
async function emitFormatted(
  path: string,
  pricing: Record<string, ModelPricing>,
  generatedAt: string,
): Promise<string> {
  writeFileSync(path, serialize(pricing, generatedAt, 'litellm-main'));
  await formatFile(path);
  return readFileSync(path, 'utf8');
}

async function main(): Promise<void> {
  const json = await fetchSource(SOURCE_URL);

  if (json === null) {
    warn('using committed snapshot (offline fallback)');
    if (!existsSync(outPath)) {
      warn('no committed snapshot to fall back to — leaving an empty table');
    }
    return; // keep the committed file untouched
  }

  const pricing = compact(json);
  const count = Object.keys(pricing).length;
  if (count === 0) {
    warn('source yielded 0 priced models — keeping committed snapshot');
    return;
  }

  const prior = existsSync(outPath) ? readFileSync(outPath, 'utf8') : '';
  // Write the canonical (oxfmt-formatted) snapshot reusing the prior timestamp,
  // then compare on priced content only. If unchanged, we're done — the file is
  // byte-identical to prior (regeneration proof holds). Only when prices changed
  // do we bump GENERATED_AT and re-emit.
  const generatedAt = existingGeneratedAt(prior);
  const next = await emitFormatted(outPath, pricing, generatedAt);

  if (next === prior) {
    warn(`no change (${count} models)`);
    return;
  }
  // The file changed. If the priced content is identical and only the timestamp
  // would move, keep the prior file untouched (no churn). Otherwise the prices
  // genuinely changed: bump GENERATED_AT and re-emit the canonical form.
  if (prior !== '' && withoutTimestamp(next) === withoutTimestamp(prior)) {
    writeFileSync(outPath, prior);
    warn(`no change (${count} models)`);
    return;
  }
  await emitFormatted(outPath, pricing, new Date().toISOString());
  warn(`wrote ${outPath} (${count} models)`);
}

await main();
