// Auto-generated from plugin/ directory. Do not edit manually.
// Regenerate with: bun run generate-plugin-embed

export const PLUGIN_FILES: Record<string, string> = {
  '.claude-plugin/plugin.json':
    '{\n  "name": "sessions",\n  "description": "Skills for summarizing and recalling AI coding sessions across Claude Code, Codex, and Pi.",\n  "version": "1.0.0",\n  "author": {\n    "name": "Nick Nisi",\n    "email": "nick@nisi.org"\n  },\n  "homepage": "https://github.com/nicknisi/sessions",\n  "repository": "https://github.com/nicknisi/sessions",\n  "license": "MIT",\n  "keywords": ["sessions", "context", "weekly-summary", "standup", "recall", "metrics", "activity", "digest"]\n}\n',
  '.codex-plugin/plugin.json':
    '{\n  "name": "sessions",\n  "description": "Skills for summarizing and recalling AI coding sessions across Claude Code, Codex, and Pi.",\n  "version": "1.0.0",\n  "author": {\n    "name": "Nick Nisi",\n    "email": "nick@nisi.org"\n  },\n  "homepage": "https://github.com/nicknisi/sessions",\n  "repository": "https://github.com/nicknisi/sessions",\n  "license": "MIT",\n  "keywords": ["sessions", "context", "weekly-summary", "standup", "recall", "metrics", "activity", "digest"],\n  "skills": "./skills/",\n  "interface": {\n    "displayName": "Sessions",\n    "shortDescription": "Summarize and recall AI coding sessions",\n    "category": "Productivity"\n  }\n}\n',
  '.cursor-plugin/plugin.json':
    '{\n  "name": "sessions",\n  "description": "Skills for summarizing and recalling AI coding sessions across Claude Code, Codex, and Pi.",\n  "version": "1.0.0",\n  "author": {\n    "name": "Nick Nisi",\n    "email": "nick@nisi.org"\n  },\n  "homepage": "https://github.com/nicknisi/sessions",\n  "repository": "https://github.com/nicknisi/sessions",\n  "license": "MIT",\n  "keywords": ["sessions", "context", "weekly-summary", "standup", "recall", "metrics", "activity", "digest"]\n}\n',
  '.mcp.json':
    '{\n  "mcpServers": {\n    "sessions": {\n      "command": "sessions",\n      "args": ["--mcp"]\n    }\n  }\n}\n',
  'skills/context/SKILL.md':
    '---\nname: context\ndescription: >-\n  Load a context primer for the current repo before starting work. Use when the\n  user says "what was I doing here", "catch me up on this repo", "context primer",\n  "what\'s the open thread", or when resuming work on a codebase after a break.\nargument-hint: optional repo path\n---\n\nSynthesize a prose context primer from past sessions on this repo.\n\n## Steps\n\n1. **Fetch the primer.** Call the `get_context_primer` MCP tool (pass `cwd` if a path was given).\n2. **Synthesize, don\'t dump.** From the JSON, write: prior decisions, what was tried/abandoned, and the current open thread.\n3. **Anchor the open thread** on the most-recent session\'s `closing` — `closing.user` is the last thing you actually typed and `closing.assistant` is the assistant\'s last substantive reply (outcomes like "PR is up: …" survive); `branch` is the branch you left off on.\n4. **Keep it tight** — a short brief the user can act on, not a transcript.\n\n## Guidelines\n\n- Prefer the most recent + most-edited files as the likely active surface.\n- If the primer is empty, say so plainly; don\'t invent history.\n',
  'skills/recall/SKILL.md':
    '---\nname: recall\ndescription: >-\n  Recall what was done on a specific project or topic. Use when the user says\n  "what did I do on [project]", "recall [topic]", "history of [project]",\n  "when did I last work on [thing]", or wants to remember past work on a\n  specific codebase or feature.\nargument-hint: project name or path\n---\n\nRecall past work on a specific project or topic.\n\n## Steps\n\n1. **Identify the target.** The user\'s argument is a project name, path, or topic. If it looks like a path, use it directly. If it\'s a name, search for it.\n\n2. **Search sessions.** Call `search_sessions` with:\n   - `query`: the topic/keyword if searching by content\n   - `project`: the path if filtering by project directory\n   - `limit`: 20\n\n3. **Get context for top results.** For the most relevant sessions (up to 5), call `get_session_messages` with:\n   - `filePath`: from the search results\n   - `limit`: 20\n\n4. **Summarize the history.** Write a chronological summary:\n\n   ### Sessions on {project/topic}\n\n   For each relevant session:\n   - **{date}** ({tool}) — What was worked on, key decisions made, outcome\n\n   **Overall arc:** How the work evolved across sessions.\n\n## Guidelines\n\n- Order chronologically (oldest first) to show the arc of work.\n- If the user gives a vague name, try both `search_sessions` (keyword search) and `get_activity_digest` (project path filter) to find matches.\n- Focus on decisions and outcomes, not implementation details.\n- If there are many sessions, group by phase or milestone rather than listing each one.\n',
  'skills/session-metrics/SKILL.md':
    '---\nname: session-metrics\ndescription: >-\n  Show usage metrics and analytics for AI coding sessions. Use when the user\n  asks "how much have I been coding", "session stats", "show me metrics",\n  "tool usage", "which tool do I use most", "active hours", or wants\n  analytics about their AI coding tool usage.\nargument-hint: time period (e.g., "past week", "may", "past month")\n---\n\nShow session usage metrics and analytics.\n\n## Steps\n\n1. **Parse the time period.** Convert the user\'s argument to a date range (YYYY-MM-DD). Default to the past 7 days if no period specified. Common inputs: "past week", "this month", "past 30 days", "may 2026".\n\n2. **Fetch metrics.** Call `get_session_metrics` with:\n   - `startDate` and `endDate` from the parsed range\n\n3. **Format the dashboard:**\n\n   ### Session Metrics: {start} to {end}\n\n   **Overview**\n   - {total sessions} sessions | {total messages} messages\n   - Tools: {breakdown with counts}\n\n   **Top Projects** (table: project, sessions, messages)\n   List the top 10 by session count.\n\n   **Daily Activity** (table or mini-chart: date, sessions, messages)\n   Show each day in the range.\n\n   **Active Hours**\n   Render the hours heatmap as a simple bar chart or table showing which hours of the day have the most sessions. Convert to local time labels (e.g., "9am", "2pm").\n\n## Guidelines\n\n- Round percentages to whole numbers.\n- For active hours, group into time blocks if the data is sparse (morning/afternoon/evening/night).\n- If a tool has zero sessions, omit it from the breakdown.\n- Keep the formatting clean — this should be pasteable into a document or message.\n',
  'skills/standup/SKILL.md':
    '---\nname: standup\ndescription: >-\n  Generate a quick standup summary of yesterday and today\'s AI coding sessions.\n  Use when the user says "standup", "what did I do yesterday", "daily summary",\n  "what have I been working on", or needs a quick recap for a standup meeting.\n---\n\nGenerate a brief standup-style summary.\n\n## Steps\n\n1. **Calculate dates.** Yesterday and today in YYYY-MM-DD format.\n\n2. **Fetch the digest.** Call `get_activity_digest` with:\n   - `startDate`: yesterday\n   - `endDate`: today\n   - `detail`: `"compact"`\n\n3. **Format as a standup.** Write three sections, each 2-4 bullets max:\n\n   **Yesterday:**\n   - What was accomplished (project: brief description)\n\n   **Today (so far):**\n   - What\'s been started or is in progress\n\n   **Carrying forward:**\n   - Anything that spans both days or is unfinished\n\n## Guidelines\n\n- Keep it terse. Each bullet should be one line.\n- Group by project if multiple sessions touched the same project.\n- Skip noise — only mention substantive sessions.\n- If yesterday had no sessions, say so and focus on today.\n- Format for pasting into Slack or a standup thread.\n',
  'skills/weekly-summary/SKILL.md':
    '---\nname: weekly-summary\ndescription: >-\n  Generate a comprehensive summary of AI coding sessions from the past week.\n  Use when the user says "weekly summary", "what did I do this week",\n  "summarize my week", "weekly recap", "week in review", or asks for a\n  summary of recent work across projects.\n---\n\nGenerate a weekly summary of the user\'s AI coding sessions.\n\n## Steps\n\n1. **Get the date range.** Calculate the start date (7 days ago) and end date (today) in YYYY-MM-DD format.\n\n2. **Fetch the digest.** Call `get_activity_digest` with:\n   - `startDate`: 7 days ago\n   - `endDate`: today\n   - `detail`: `"highlights"` (first + last user messages for substantive sessions)\n\n3. **Review the digest.** Read the response directly — do NOT send it to a subagent. The highlights mode is compact enough to process inline. For each day, identify:\n   - Which projects were worked on and what was accomplished\n   - Key decisions, pivots, or discoveries (visible in the first/last message pairs)\n   - Recurring themes across projects\n\n4. **Drill into key sessions (optional).** If any sessions look particularly significant (high message count, interesting topic) but the highlights don\'t capture enough detail, call `get_session_messages` on those specific sessions (up to 5) using the `filePath` from the digest.\n\n5. **Write the summary.** Structure it as:\n\n   ### Week of {start} - {end}\n\n   **By the numbers:** {total sessions} sessions, {total messages} messages across {project count} projects.\n\n   **Day-by-day:**\n   For each day with activity, write 2-4 bullet points capturing the most significant work. Be specific — name projects, features, and outcomes. Skip days with no meaningful activity.\n\n   **Highlights:** The 3-5 most significant accomplishments across the entire week.\n\n   **Themes:** Recurring work streams or focus areas (e.g., "SDK development", "infrastructure", "bug fixes").\n\n## Guidelines\n\n- Process the digest inline. Do not spawn a subagent to read it.\n- Be specific. Quote project names, feature descriptions, and tool names.\n- The first message shows intent; the last message shows outcome. Use both to capture the arc.\n- Skip noise — 1-message sessions and test sessions are not worth mentioning.\n- If a project appears across multiple days, note the arc of progress.\n- Write for the user to review, not for a third party. Use "you" not "the user".\n',
};
